Combination of SR=MonoHFatJetSelection_JetAndLeptonVeto_DataCard_monoHbbM1200_300GeV_MonoHbb_13TeV.txt  ZbCR=ZLight_DataCard_monoHbbM1200_300GeV_MonoHbb_13TeV.txt  WbCR=WHeavy_DataCard_monoHbbM1200_300GeV_MonoHbb_13TeV.txt
imax 3 number of bins
jmax 5 number of processes minus 1
kmax 47 number of nuisance parameters
----------------------------------------------------------------------------------------------------------------------------------
shapes *     SR    MonoHFatJetSelection_JetAndLeptonVeto.root $PROCESS $PROCESS_$SYSTEMATIC
shapes *     WbCR  histfacFatJet_WHeavy.root $PROCESS $PROCESS_$SYSTEMATIC
shapes *     ZbCR  histfacFatJet_ZLight.root $PROCESS $PROCESS_$SYSTEMATIC
----------------------------------------------------------------------------------------------------------------------------------
bin          SR           ZbCR         WbCR       
observation  38.0         280.0        107.0      
----------------------------------------------------------------------------------------------------------------------------------
bin                                             SR                SR                SR                SR                SR                SR                ZbCR              ZbCR              ZbCR              ZbCR              ZbCR              ZbCR              WbCR              WbCR              WbCR              WbCR              WbCR              WbCR            
process                                         monoHbbM1200_300  DIBOSON           ZH                TT                WJets             DYJets            monoHbbM1200_300  DIBOSON           ZH                TT                WJets             DYJets            monoHbbM1200_300  DIBOSON           ZH                TT                WJets             DYJets          
process                                         0                 1                 2                 3                 4                 5                 0                 1                 2                 3                 4                 5                 0                 1                 2                 3                 4                 5               
rate                                            375.0985          1.4606            0.8636            9.5527            12.2884           25.4295           89.5399           15.1202           0.3205            25.6488           108.1320          182.3071          0.7359            2.8934            0.0025            65.2189           46.8142           0.3705          
----------------------------------------------------------------------------------------------------------------------------------
CMS_monoHbb_DYjets_stat   lnN                   -                 -                 -                 -                 -                 1.04              -                 -                 -                 -                 -                 1.01              -                 -                 -                 -                 -                 1.32            
CMS_monoHbb_HMass       lnN                     1.100/0.900       -                 -                 -                 -                 0.900/1.100       1.100/0.900       -                 -                 -                 -                 0.900/1.100       1.100/0.900       -                 -                 -                 -                 0.900/1.100     
CMS_monoHbb_HMassShower   lnN                   1.07              -                 -                 -                 -                 1.07              1.07              -                 -                 -                 -                 1.07              1.07              -                 -                 -                 -                 1.07            
CMS_monoHbb_ST          lnN                     -                 -                 -                 1.25              -                 -                 -                 -                 -                 1.25              -                 -                 -                 -                 -                 1.25              -                 -               
CMS_monoHbb_TT_stat     lnN                     -                 -                 -                 1.01              -                 -                 -                 -                 -                 -                 -                 -                 -                 -                 -                 -                 -                 -               
CMS_monoHbb_ToppT       lnN                     -                 -                 -                 1.2               -                 -                 -                 -                 -                 1.2               -                 -                 -                 -                 -                 1.2               -                 -               
CMS_monoHbb_VV          lnN                     -                 1.25              -                 -                 -                 -                 -                 1.25              -                 -                 -                 -                 -                 1.25              -                 -                 -                 -               
CMS_monoHbb_VV_stat     lnN                     -                 1.22              -                 -                 -                 -                 -                 1.07              -                 -                 -                 -                 -                 1.16              -                 -                 -                 -               
CMS_monoHbb_WHFunc      lnN                     -                 -                 -                 -                 1.1               -                 -                 -                 -                 -                 1.1               -                 -                 -                 -                 -                 1.1               -               
CMS_monoHbb_Wjets_stat   lnN                    -                 -                 -                 -                 1.12              -                 -                 -                 -                 -                 1.04              -                 -                 -                 -                 -                 1.06              -               
CMS_monoHbb_eff_b       lnN                     1.07              1.07              1.07              -                 -                 -                 1.07              1.07              1.07              -                 -                 -                 1.07              1.07              1.07              -                 -                 -               
CMS_monoHbb_ewk         shape                   -                 -                 -                 -                 1.0               1.0               -                 -                 -                 -                 1.0               1.0               -                 -                 -                 -                 1.0               1.0             
CMS_monoHbb_fake_b_13TeV   lnN                  1.03              -                 1.03              -                 -                 -                 1.03              -                 1.03              -                 -                 -                 1.03              -                 1.03              -                 -                 -               
CMS_monoHbb_metUnclusteredEn   lnN              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05            
CMS_monoHbb_monoH_stat   lnN                    -                 -                 -                 -                 -                 -                 -                 -                 -                 -                 -                 -                 1.02              -                 -                 -                 -                 -               
CMS_monoHbb_pdf         lnN                     -                 1.05              1.05              1.05              1.05              1.05              -                 1.05              1.05              1.05              1.05              1.05              -                 1.05              1.05              1.05              1.05              1.05            
CMS_monoHbb_pdf_sig     lnN                     1.05              -                 -                 -                 -                 -                 1.05              -                 -                 -                 -                 -                 1.05              -                 -                 -                 -                 -               
CMS_monoHbb_res_j       lnN                     1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05            
CMS_monoHbb_scaleF      shape                   1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -               
CMS_monoHbb_scaleR      shape                   1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -               
CMS_monoHbb_scale_j     lnN                     1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05              1.05            
CMS_monoHbb_trigger_MET   lnN                   1.03              1.03              1.03              -                 -                 -                 1.03              1.03              1.03              -                 -                 -                 1.03              1.03              1.03              -                 -                 -               
DIBOSON_stat_bin1       shape                   -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -               
DIBOSON_stat_bin2       shape                   -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -               
DIBOSON_stat_bin3       shape                   -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -               
DYJets_stat_bin1        shape                   -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0             
DYJets_stat_bin2        shape                   -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0             
DYJets_stat_bin3        shape                   -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0             
QCDscale_VH             lnN                     1.04              -                 1.04              -                 -                 -                 1.04              -                 1.04              -                 -                 -                 1.04              -                 1.04              -                 -                 -               
QCDscale_VV             lnN                     -                 1.04              -                 -                 -                 -                 -                 1.04              -                 -                 -                 -                 -                 1.04              -                 -                 -                 -               
TT_stat_bin1            shape                   -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -               
TT_stat_bin2            shape                   -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -               
TT_stat_bin3            shape                   -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -               
WJets_stat_bin1         shape                   -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -               
WJets_stat_bin2         shape                   -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -               
WJets_stat_bin3         shape                   -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -               
ZH_stat_bin1            shape                   -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -               
ZH_stat_bin2            shape                   -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -               
ZH_stat_bin3            shape                   -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -               
lumi_13TeV              lnN                     1.026             1.026             1.026             -                 -                 -                 1.026             1.026             1.026             -                 -                 -                 1.026             1.026             1.026             -                 -                 -               
monoHbbM1200_300_stat_bin1   shape              1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -               
monoHbbM1200_300_stat_bin2   shape              1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -               
monoHbbM1200_300_stat_bin3   shape              1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -                 1.0               -                 -                 -                 -                 -               
pdf_gg                  lnN                     -                 -                 1.5               -                 -                 -                 -                 -                 1.5               -                 -                 -                 -                 -                 1.5               -                 -                 -               
pdf_qqbar               lnN                     1.01              1.01              1.01              -                 -                 -                 1.01              1.01              1.01              -                 -                 -                 1.01              1.01              1.01              -                 -                 -               
CMS_monoHbb_WJFracSR      lnN                     -             -             -          1.30           1.30           -             -             -             -             -            -           -             -             -             -             -             -           -
##monoHbbM2500_700  DIBOSON           ZH                TT                WJets             DYJets
CMS_monoHbb_lepVeto      lnN                     -          -      -      1.02/0.98       1.02/0.98       -      -          -      -      1.02/0.98       1.02/0.98       -    -          -      -      1.02/0.98       1.02/0.98       -

ZjHF_norm   rateParam  ZbCR DYJets 1 [0.5,1.6]
ZjHF_norm   rateParam  SR   DYJets 1 [0.5,1.6]

Wbj_norm   rateParam  ZbCR  WJets 1 [0.5,1.5]
Wbj_norm   rateParam  WbCR  WJets 1 [0.5,1.5]
Wbj_norm   rateParam  WbCR  TT 1 [0.5,1.5]

